### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by jj20466** [RSDuck/craftus_reloaded#1]
![1503456316782-1907238166](https://user-images.githubusercontent.com/30852004/29596543-3219c934-87f0-11e7-8de3-3cc705eeadfd.jpg)
I deleted testwelt then created a flat world but i just have a blue screen and i created a smea world after and got the same results.i have n3ds xl 11.3.9-36E with luma 8.1.1 using the cia and 3dsx versions of craftus reloaded 0.2

**Comment by jj20466** [comment]
Update: i some how got a smea type world to load not sure how though and you should make the jump button on n3ds B or A and the ZL  & ZR to change blocks.
Update2: there is a hidden world in the load menu and if i load it i can actually get a world to play on which is a smea type
![1503457218408-1087364994](https://user-images.githubusercontent.com/30852004/29596965-48f11994-87f2-11e7-915e-c7de9c5d94b4.jpg)

**Comment by RSDuck** [comment]
on the first screenshot, did you fell out of the world? The Y-Coordinate of you very low, try pressing Select to open the command prompt and then enter `/tp 0 20 0`(on a flat world) or `/tp 0 80 0`(on a smea world).

I tried by myself and creating a new world under certain cirmstances leaves you add 0 -800 -0. I think I already found the orgin of the problem and fixed it(the problem is that you can fall faster than Craftus checks the collisions).

Regarding the hidden world, is it possible that you once confirmed to create a world, without entering a name? I just tried it and it is possible, I forgot to add a minimum character limit.

**Comment by jj20466** [comment]
I did the command you told me to do and i spawn back on land but when i
actually created the worlds it must of spawned me under map cause i didnt
spawn on land at all and dug down,e not typing anything for the name of the
world could explain why it has an invisible name but when did the world
have land when the other worlds spawn under it and i figured out how to
change my controls but would be nice if there was a pause menu to do that.

**Comment by RSDuck** [comment]
try the newest [release](https://github.com/RSDuck/craftus_reloaded/releases), I made just a few minutes ago, I think it fixes exactly what you described(that you spawn under the world).
Adding such a menu would be nice, but I have currently other priorities, implementing it would take time I could spend on implementing light or fixing game breaking bugs.

**Comment by yerWizard** [comment]
I downloaded 0.21 CIA version and i still get this problem.

**Comment by jj20466** [comment]
I created 3 worlds of flat and i spawned under map and when i was creating
the world 2 of them crashed and j had to hold my power button to turn it
off and the worlds never got created then i did the same with smea but it
only crashed once.i was using version 0.2.1

**Comment by RSDuck** [comment]
I just tried the cia release(I always use the 3dsx version to debug, because it doesn't need to be installed) and I could instantly reproduce your problem, which still existed on the cia release(it existed before 0.21 also on the 3dsx version, caused by another mistake).

I think I found the orgin of the problem with the cia file. Can you please try the cia, inside of the zip?
[craftus-0.22-test.zip](https://github.com/RSDuck/craftus_reloaded/files/1245525/craftus-0.22-test.zip)

**Comment by yerWizard** [comment]
I tried the cia and it fixed the problem, now i spawn several blocks above the terrain as intended i guess.

**Comment by jj20466** [comment]
I spawned on the land like intended but lucky we dont have health or i
would be dead hahaha

**Comment by RSDuck** [comment]
yes it is intended that you spawn at height of 80 blocks :)
splendid, then I will make a release now
